services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6380:6379"

  garnet:
    image: ghcr.io/microsoft/garnet:latest
    ports:
      - "6381:6379"
