// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestMonitoring.Library.Context;

#nullable disable

namespace RequestMonitoring.Library.Migrations
{
    [DbContext(typeof(DomainListsContext))]
    [Migration("20260411153936_AddQuotaType")]
    partial class AddQuotaType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("RequestMonitoring.Library.Enitites.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DomainStatusTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.HasKey("Id");

                    b.HasIndex("DomainStatusTypeId");

                    b.ToTable("domain");
                });

            modelBuilder.Entity("RequestMonitoring.Library.Enitites.DomainStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("DomainStatusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allowed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Greylisted"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Unauthorized"
                        });
                });

            modelBuilder.Entity("RequestMonitoring.Library.Enitites.Quota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DomainId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("domain_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastResetAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_reset_at");

                    b.Property<int?>("MaxRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_requests");

                    b.Property<int?>("PeriodSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("period_seconds");

                    b.Property<long>("RequestCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("request_count");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .IsUnique();

                    b.ToTable("quota");
                });

            modelBuilder.Entity("RequestMonitoring.Library.Enitites.Domain", b =>
                {
                    b.HasOne("RequestMonitoring.Library.Enitites.DomainStatusType", "DomainStatusType")
                        .WithMany()
                        .HasForeignKey("DomainStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomainStatusType");
                });

            modelBuilder.Entity("RequestMonitoring.Library.Enitites.Quota", b =>
                {
                    b.HasOne("RequestMonitoring.Library.Enitites.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });
#pragma warning restore 612, 618
        }
    }
}
