// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestMonitoringLibrary.Context;

#nullable disable

namespace RequestMonitoringLibrary.Migrations
{
    [DbContext(typeof(DomainListsContext))]
    partial class DomainListsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RequestMonitoringLibrary.Enitites.Domain.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DomainStatusTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.HasKey("Id");

                    b.HasIndex("DomainStatusTypeId");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("RequestMonitoringLibrary.Enitites.Domain.DomainStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("DomainStatusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allowed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Greylisted"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Unauthorized"
                        });
                });

            modelBuilder.Entity("RequestMonitoringLibrary.Enitites.Domain.Domain", b =>
                {
                    b.HasOne("RequestMonitoringLibrary.Enitites.Domain.DomainStatusType", "DomainStatusType")
                        .WithMany()
                        .HasForeignKey("DomainStatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomainStatusType");
                });
#pragma warning restore 612, 618
        }
    }
}
